<?php

/**
 * CineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cine');
    }

    
    public function getTodos(){
        return $this->createQuery('cine')
               ->execute();
    }
}

