<?php

/**
 * Pelicula
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cine
 * @subpackage model
 * @author     andres
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Pelicula extends BasePelicula
{
    public function __toString(){
      return $this->getTitulo().'   '.$this->getDuracion().'   '.$this->getDirector();
      }

}
