<?php

/**
 * PeliculaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PeliculaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PeliculaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pelicula');
    }
<<<<<<< HEAD
}
=======
    
    public function getTodas(){
      return $this->createQuery('pelicula')->execute();
    }
}
>>>>>>> 6eaa45c460819ebacddfb506dc87e4597108a491
