<?php

/**
 * PrecioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrecioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrecioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Precio');
    }

    public function getPrecio($dia, $tipoProyeccion){
        //para que hace falta que me pase el dia si solo vamos a probar si es el dia de hoy?
        $fecha = Doctrine::getTable('FechaEspecial')->getDia(date('Y-m-d'))->getTipoDia();
        //$this->precio = Doctrine::getTable('Precio')->getDia(date('Y-m-d'));

        $objetoPrecio=$this->createQuery('precio')
               ->where('precio.tipoPrecio=\''.$fecha.'\'')
               ->fetchOne();
               if ($tipoProyeccion=="2D"){
                    return $objetoPrecio->valor2D;
               }else{
                    return $objetoPrecio->valor3D;
               }
               
               
           }

    }

