<?php

/**
 * PrecioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrecioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrecioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Precio');
    }
}