<?php

/**
 * SalaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sala');
    }
    
    public function getTodas(){
        return $this->createQuery('sala')->execute();
    }
    
    public function getFiltradasPorCine($cine)
    {
         return $this->createQuery('sala')->where('sala.cineId='.$cine->id)->execute();
    }
}

