<?php

/**
 * SalaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Sala');
    }
}